@host = http://127.0.0.1:8000

### Create Token
POST {{host}}/v1/auth/token
Content-Type: application/json

{
  "username": "john.doe",
  "password": "john"
}

### Verify Token
POST {{host}}/v1/auth/verify
Content-Type: application/json

{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJtYXJrIFNhaSIsImV4cCI6MTY1NDkyMjU0Nn0.W7YlRoOAKcCtnqMeHWlusdHQWzu7I-7wh8pvj6_VdZY"
}