@host = http://127.0.0.1:8000

### Create Token
GET {{host}}/v1/auth/token
Content-Type: application/json

{
  "username": "mark Sai",
  "password": "simdesierto"
}

### Verify Token
GET {{host}}/v1/auth/verify
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJtYXJrIFNhaSIsImV4cCI6MTY1NDg1NzM0M30.BCDsS4eEXP42E6rf1TfMzXma1JnWfwksZxa5QXJZO78
Content-Type: application/json

### Customers
GET {{host}}/customer/v1/customers
Content-Type: application/json