@host = http://127.0.0.1:8000

### Create Token
GET {{host}}/v1/auth/token
Content-Type: application/json

{
  "username": "mark Sai",
  "password": "simdesierto"
}

### Verify Token
GET {{host}}/v1/auth/verify
Content-Type: application/json

{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJtYXJrIFNhaSIsImV4cCI6MTY1NDkyMjU0Nn0.W7YlRoOAKcCtnqMeHWlusdHQWzu7I-7wh8pvj6_VdZY"
}

# ### Verify Token
# GET {{host}}/v1/auth/verify
# Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NywidXNlcm5hbWUiOiJzdGV2ZS5oYXJ2ZXkiLCJleHAiOjE2NTQ3ODQ5NTl9.vqG5HdSWTkslznE3X07GyosuQQSKBC626XPx2nOfAAU
# Content-Type: application/json

# ### Customers
# GET {{host}}/customer/v1/customers
# Content-Type: application/json