# Generated by Django 3.1.1 on 2020-10-06 16:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_datereg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dateregistered', models.DateField(default=datetime.datetime(2020, 10, 7, 0, 23, 6, 599032))),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.DateField(default=datetime.datetime(2020, 10, 7, 0, 23, 6, 599032))),
                ('birthplace', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='datereg',
            field=models.DateField(default=datetime.datetime(2020, 10, 7, 0, 23, 6, 597076)),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.person')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('dashboard.person',),
        ),
    ]
