# Generated by Django 3.1.1 on 2020-10-09 04:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20201008_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 12, 2, 39, 873293)),
        ),
        migrations.AlterField(
            model_name='person',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 12, 2, 39, 873293)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datereg',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 12, 2, 39, 873293)),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
