# Generated by Django 3.1.1 on 2020-10-09 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20201009_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 15, 29, 8, 378737)),
        ),
        migrations.AlterField(
            model_name='person',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 15, 29, 8, 378737)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datereg',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 15, 29, 8, 377710)),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(max_length=5),
        ),
    ]
