# Generated by Django 3.1.1 on 2020-10-16 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20201017_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 10, 17, 1, 4, 28, 183665)),
        ),
        migrations.AlterField(
            model_name='person',
            name='dateregistered',
            field=models.DateField(default=datetime.datetime(2020, 10, 17, 1, 4, 28, 183665)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datereg',
            field=models.DateField(default=datetime.datetime(2020, 10, 17, 1, 4, 28, 181608)),
        ),
    ]
