# Generated by Django 3.1.7 on 2022-06-07 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20220607_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2022, 6, 7, 14, 36, 44, 507124)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datereg',
            field=models.DateField(auto_now_add=True),
        ),
    ]
