# Generated by Django 3.1.7 on 2022-06-08 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20220607_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 12, 4, 54, 486933)),
        ),
    ]
