# Generated by Django 4.0.5 on 2022-06-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_person_birthdate'),
        ('dashboard', '0023_auto_20220608_1204'),
    ]

    operations = [
    ]
