# Generated by Django 4.0.5 on 2022-06-09 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_merge_20220609_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2022, 6, 9, 19, 45, 15, 99732)),
        ),
    ]
