# Generated by Django 4.0.5 on 2022-06-08 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_merge_20220608_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 19, 54, 48, 952262)),
        ),
    ]
