# Generated by Django 4.0.5 on 2022-06-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_merge_20220609_0048'),
        ('dashboard', '0024_merge_20220609_1945'),
    ]

    operations = [
    ]
