# Generated by Django 4.0.3 on 2022-06-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_merge_20220609_0048'),
        ('dashboard', '0025_alter_person_birthdate'),
    ]

    operations = [
    ]
